### PR TITLE
Implement matvec in blocked discrete operator.

### PR DESCRIPTION
**Pull request by evantwout**
Implemented the _matvec() function in the class BlockedDiscreteOperator.

This is necessary for custom LinearOperators that work for 1D arrays only. See below an example.

```python
import bempp.api
import numpy as np
from scipy.sparse.linalg.interface import LinearOperator

grid = bempp.api.shapes.sphere(h=1)
space = bempp.api.function_space(grid,'P',1)
id_op = bempp.api.operators.boundary.sparse.identity(space,space,space)

ndof = space.global_dof_count
linop = LinearOperator([ndof, ndof], matvec=lambda x:x*np.arange(ndof))

op_wf = linop * id_op.weak_form()
op_block = bempp.api.assembly.blocked_operator.BlockedDiscreteOperator([[op_wf]])

# multiplication with the operator works
print(op_block[0,0]*np.ones(ndof))

# multiplication with the block operator does not work without the matvec() function
# this is because the custom LinearOperator only works for 1D arrays (n,) not 2D arrays (n,1)
print(op_block*np.ones(ndof))
```

### CODE REVIEW

**Comment by tbetcke** [comment]
Hi, I think this would be more a problem of the custom linear operator. Anything that derives from Scipy LinearOperator needs to implement either _matvec or _matmat. The other routine is then automatically implemented from the default. See documentation at (https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html).

**Comment by evantwout** [comment]
Hi Timo, I agree that this issue can be solved by adapting the LinearOperator accordingly. The reason I implemented the matvec nonetheless is that, at the moment, this example works for a boundary operator but throws an error for a blocked operator. This is inconsistent behaviour that can create confusion. I am open to other suggestions to solve this issue.

**Comment by tbetcke** [comment]
Hi. I agree that this is inconsistent. The problem is that your current patch essentially duplicates some quite intricate piece of code for something that should not need to be handled on our side. The fundamental issue is the very inconsistent behavior of the various LinearOperator methods in Scipy. Happy to put in everything that allows us not to write the same function twice. Maybe, we could have a single routine that is called by both _matvec and _matmat?

**Comment by evantwout** [comment]
I looked into this issue in more detail.

First, the (blocked) discrete boundary operators of bempp-cl are subclasses of the SciPy LinearOperator class. Whereas a discrete boundary operator overloads a `_matvec` function, the blocked discrete operator overloads the `_matmat` function. Hence, the expected behaviour of a multiplication (`*` or `dot`) is the following.
 1. For the discrete boundary operator, arrays of shape (n,) and (n,1) are handled directly by the custom matvec. For arrays of shape (n,m), the default matmat calls the custom matvec for each column by taking m arrays of shape (n,1).
 1. For the blocked boundary operator, arrays of shape (n,m) are handled directly by the custom matmat. For arrays of shape (n,1), the default matvec calls the custom matmat. For arrays of shape (n,), the default matvec reshapes the array to (n,1), calls the matmat, and reshapes the output to a (n,) array.

Second, the custom LinearOperator defined above (`LinearOperator([ndof, ndof], matvec=lambda x:x*np.arange(ndof))`) involves the array `np.arange(ndof)` of shape (n,). In Numpy, the expected behaviour of `a*b` is as follows.
1. If `a` of shape (n,) and `b` of shape (n,) the result is an array of shape (n,), given by pointwise multiplication.
2. If `a` of shape (n,1) and `b` of shape (m,) the result is an array of shape (n,m), given by a vector product.

In the example of this pull request, a product of the custom linear operator and a boundary operator is defined and multiplied with `np.ones(ndof)`, which is a (n,) array. Hence, the custom matvec of the boundary operator is called for a (n,) array and then the custom linear operator is called for a (n,) array. This works as expected. In the case of the blocked boundary operator with this operator product, the workflow is as follows.
1. The blocked boundary operator has a custom matmat. Hence, the input array is converted to a (n,1) array and the matmat is called.
2. Inside the matmat of the blocked boundary operator, the function `dot` of each block operator is called with a (n,1) array.
3. The discrete boundary operator returns a (n,1) array, which is the input for the custom LinearOperator. Due to the behaviour explained above, the output of the custom LinearOperator is a (n,n) array.
4. The function `matvec` of the base LinearOperator class receives the (n,n) array and tries to convert it to a (n,1) array, which should be the output shape. The shape mismatch causes the error.

In summary, this issue is expected behaviour. The root cause is that the custom LinearOperator does not work correctly for a (n,1) array, while it works correctly for a (n,) array. Actually, `linop*np.ones(ndof).reshape([ndof,1])` throws the same error. According to the documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html, see Notes), it is the responsibility of the user to guarantee that a custom `matvec` works correctly for both (n,) and (n,1) arrays. This is not automatically checked by SciPy, though.

The question is what to do if someone defines a custom `LinearOperator` that works correctly for (n,) arrays but not (n,1) arrays. There are basically two options:
 1. Leave it as it was. Bempp-cl (more precisely, SciPy) will throw an error for blocked discrete operators but not for discrete operators. This is a responsibility of the user since the SciPy documentation states that custom linear operators defined by a matvec should work correctly for both (n,) and (n,1) arrays.
 1. Adapt bempp-cl such that it works for these incorrectly defined linear operators. This entails avoiding reshapes from (n,) to (n,1) arrays. There are two patches:
  a. Use both `matvec` and `matmat`, as in this pull request. This works but has duplicated code.
  b. Use only `matvec` and remove `matmat`. I tested this and it works with a small change to the code, but it might impact maintainability.

I am fine with any of these options and leave the decision to the admins.

**Pull request merged**
